### ISSUE TITLE
artifacts left after deletion of joint and it lead to broke recompile. Inherited from CROSS.

### ISSUE THREAD

**Issue by drfenixion** [drfenixion/freecad.cross#7]
15:29:49  Traceback (most recent call last):
  File "/home/ubuntu/.local/share/FreeCAD/Mod/freecad.cross/freecad/cross/robot_proxy.py", line 231, in execute
    self.set_joint_enum()
  File "/home/ubuntu/.local/share/FreeCAD/Mod/freecad.cross/freecad/cross/robot_proxy.py", line 376, in set_joint_enum
    child_links += get_possible_child_links(joint)
  File "/home/ubuntu/.local/share/FreeCAD/Mod/freecad.cross/freecad/cross/robot_proxy.py", line 364, in get_possible_child_links
    and link.Proxy.may_be_base_link()
  File "/home/ubuntu/.local/share/FreeCAD/Mod/freecad.cross/freecad/cross/link_proxy.py", line 386, in may_be_base_link
    return self.get_ref_joint() is None
  File "/home/ubuntu/.local/share/FreeCAD/Mod/freecad.cross/freecad/cross/link_proxy.py", line 371, in get_ref_joint
    and attr_equals(self._ref_joint, 'Child', ros_name(self.link))
  File "/home/ubuntu/.local/share/FreeCAD/Mod/freecad.cross/freecad/cross/utils.py", line 77, in attr_equals
    return hasattr(instance, attr) and getattr(instance, attr) == value
<class 'ReferenceError'>: Cannot access attribute 'Child' of deleted object
15:29:49  Recompute failed!

**Comment by drfenixion** [comment]
After close FreeCAD and reopen error disappeared.
